/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as AgentsRouteImport } from "./routes/agents";
import { Route as AmpRouteImport } from "./routes/amp";
import { Route as ChangelogRouteImport } from "./routes/changelog";
import { Route as ClaudeCodeRouteImport } from "./routes/claude-code";
import { Route as ClineRouteImport } from "./routes/cline";
import { Route as CodexRouteImport } from "./routes/codex";
import { Route as CopilotRouteImport } from "./routes/copilot";
import { Route as CursorRouteImport } from "./routes/cursor";
import { Route as DeepseekTuiRouteImport } from "./routes/deepseek-tui";
import { Route as DocsRouteImport } from "./routes/docs";
import { Route as DownloadRouteImport } from "./routes/download";
import { Route as FxRouteImport } from "./routes/fx";
import { Route as GeminiRouteImport } from "./routes/gemini";
import { Route as GooseRouteImport } from "./routes/goose";
import { Route as GrokRouteImport } from "./routes/grok";
import { Route as KimiRouteImport } from "./routes/kimi";
import { Route as MistralVibeRouteImport } from "./routes/mistral-vibe";
import { Route as OpencodeRouteImport } from "./routes/opencode";
import { Route as PiRouteImport } from "./routes/pi";
import { Route as PrivacyRouteImport } from "./routes/privacy";
import { Route as TermsRouteImport } from "./routes/terms";
import { Route as AlternativesClaudeDesktopRouteImport } from "./routes/alternatives/claude-desktop";
import { Route as AlternativesCodexAppRouteImport } from "./routes/alternatives/codex-app";
import { Route as AlternativesConductorRouteImport } from "./routes/alternatives/conductor";
import { Route as AlternativesHappyCoderRouteImport } from "./routes/alternatives/happy-coder";
import { Route as AlternativesOpenchamberRouteImport } from "./routes/alternatives/openchamber";
import { Route as AlternativesOpencodeDesktopRouteImport } from "./routes/alternatives/opencode-desktop";
import { Route as AlternativesSupersetRouteImport } from "./routes/alternatives/superset";
import { Route as DocsIndexRouteImport } from "./routes/docs/index";
import { Route as DocsSplatRouteImport } from "./routes/docs/$";

const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const AgentsRoute = AgentsRouteImport.update({
  id: "/agents",
  path: "/agents",
  getParentRoute: () => rootRouteImport,
} as any);
const AmpRoute = AmpRouteImport.update({
  id: "/amp",
  path: "/amp",
  getParentRoute: () => rootRouteImport,
} as any);
const ChangelogRoute = ChangelogRouteImport.update({
  id: "/changelog",
  path: "/changelog",
  getParentRoute: () => rootRouteImport,
} as any);
const ClaudeCodeRoute = ClaudeCodeRouteImport.update({
  id: "/claude-code",
  path: "/claude-code",
  getParentRoute: () => rootRouteImport,
} as any);
const ClineRoute = ClineRouteImport.update({
  id: "/cline",
  path: "/cline",
  getParentRoute: () => rootRouteImport,
} as any);
const CodexRoute = CodexRouteImport.update({
  id: "/codex",
  path: "/codex",
  getParentRoute: () => rootRouteImport,
} as any);
const CopilotRoute = CopilotRouteImport.update({
  id: "/copilot",
  path: "/copilot",
  getParentRoute: () => rootRouteImport,
} as any);
const CursorRoute = CursorRouteImport.update({
  id: "/cursor",
  path: "/cursor",
  getParentRoute: () => rootRouteImport,
} as any);
const DeepseekTuiRoute = DeepseekTuiRouteImport.update({
  id: "/deepseek-tui",
  path: "/deepseek-tui",
  getParentRoute: () => rootRouteImport,
} as any);
const DocsRoute = DocsRouteImport.update({
  id: "/docs",
  path: "/docs",
  getParentRoute: () => rootRouteImport,
} as any);
const DownloadRoute = DownloadRouteImport.update({
  id: "/download",
  path: "/download",
  getParentRoute: () => rootRouteImport,
} as any);
const FxRoute = FxRouteImport.update({
  id: "/fx",
  path: "/fx",
  getParentRoute: () => rootRouteImport,
} as any);
const GeminiRoute = GeminiRouteImport.update({
  id: "/gemini",
  path: "/gemini",
  getParentRoute: () => rootRouteImport,
} as any);
const GooseRoute = GooseRouteImport.update({
  id: "/goose",
  path: "/goose",
  getParentRoute: () => rootRouteImport,
} as any);
const GrokRoute = GrokRouteImport.update({
  id: "/grok",
  path: "/grok",
  getParentRoute: () => rootRouteImport,
} as any);
const KimiRoute = KimiRouteImport.update({
  id: "/kimi",
  path: "/kimi",
  getParentRoute: () => rootRouteImport,
} as any);
const MistralVibeRoute = MistralVibeRouteImport.update({
  id: "/mistral-vibe",
  path: "/mistral-vibe",
  getParentRoute: () => rootRouteImport,
} as any);
const OpencodeRoute = OpencodeRouteImport.update({
  id: "/opencode",
  path: "/opencode",
  getParentRoute: () => rootRouteImport,
} as any);
const PiRoute = PiRouteImport.update({
  id: "/pi",
  path: "/pi",
  getParentRoute: () => rootRouteImport,
} as any);
const PrivacyRoute = PrivacyRouteImport.update({
  id: "/privacy",
  path: "/privacy",
  getParentRoute: () => rootRouteImport,
} as any);
const TermsRoute = TermsRouteImport.update({
  id: "/terms",
  path: "/terms",
  getParentRoute: () => rootRouteImport,
} as any);
const AlternativesClaudeDesktopRoute =
  AlternativesClaudeDesktopRouteImport.update({
    id: "/alternatives/claude-desktop",
    path: "/alternatives/claude-desktop",
    getParentRoute: () => rootRouteImport,
  } as any);
const AlternativesCodexAppRoute = AlternativesCodexAppRouteImport.update({
  id: "/alternatives/codex-app",
  path: "/alternatives/codex-app",
  getParentRoute: () => rootRouteImport,
} as any);
const AlternativesConductorRoute = AlternativesConductorRouteImport.update({
  id: "/alternatives/conductor",
  path: "/alternatives/conductor",
  getParentRoute: () => rootRouteImport,
} as any);
const AlternativesHappyCoderRoute = AlternativesHappyCoderRouteImport.update({
  id: "/alternatives/happy-coder",
  path: "/alternatives/happy-coder",
  getParentRoute: () => rootRouteImport,
} as any);
const AlternativesOpenchamberRoute = AlternativesOpenchamberRouteImport.update({
  id: "/alternatives/openchamber",
  path: "/alternatives/openchamber",
  getParentRoute: () => rootRouteImport,
} as any);
const AlternativesOpencodeDesktopRoute =
  AlternativesOpencodeDesktopRouteImport.update({
    id: "/alternatives/opencode-desktop",
    path: "/alternatives/opencode-desktop",
    getParentRoute: () => rootRouteImport,
  } as any);
const AlternativesSupersetRoute = AlternativesSupersetRouteImport.update({
  id: "/alternatives/superset",
  path: "/alternatives/superset",
  getParentRoute: () => rootRouteImport,
} as any);
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => DocsRoute,
} as any);
const DocsSplatRoute = DocsSplatRouteImport.update({
  id: "/$",
  path: "/$",
  getParentRoute: () => DocsRoute,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/agents": typeof AgentsRoute;
  "/amp": typeof AmpRoute;
  "/changelog": typeof ChangelogRoute;
  "/claude-code": typeof ClaudeCodeRoute;
  "/cline": typeof ClineRoute;
  "/codex": typeof CodexRoute;
  "/copilot": typeof CopilotRoute;
  "/cursor": typeof CursorRoute;
  "/deepseek-tui": typeof DeepseekTuiRoute;
  "/docs": typeof DocsRouteWithChildren;
  "/download": typeof DownloadRoute;
  "/fx": typeof FxRoute;
  "/gemini": typeof GeminiRoute;
  "/goose": typeof GooseRoute;
  "/grok": typeof GrokRoute;
  "/kimi": typeof KimiRoute;
  "/mistral-vibe": typeof MistralVibeRoute;
  "/opencode": typeof OpencodeRoute;
  "/pi": typeof PiRoute;
  "/privacy": typeof PrivacyRoute;
  "/terms": typeof TermsRoute;
  "/alternatives/claude-desktop": typeof AlternativesClaudeDesktopRoute;
  "/alternatives/codex-app": typeof AlternativesCodexAppRoute;
  "/alternatives/conductor": typeof AlternativesConductorRoute;
  "/alternatives/happy-coder": typeof AlternativesHappyCoderRoute;
  "/alternatives/openchamber": typeof AlternativesOpenchamberRoute;
  "/alternatives/opencode-desktop": typeof AlternativesOpencodeDesktopRoute;
  "/alternatives/superset": typeof AlternativesSupersetRoute;
  "/docs/$": typeof DocsSplatRoute;
  "/docs/": typeof DocsIndexRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/agents": typeof AgentsRoute;
  "/amp": typeof AmpRoute;
  "/changelog": typeof ChangelogRoute;
  "/claude-code": typeof ClaudeCodeRoute;
  "/cline": typeof ClineRoute;
  "/codex": typeof CodexRoute;
  "/copilot": typeof CopilotRoute;
  "/cursor": typeof CursorRoute;
  "/deepseek-tui": typeof DeepseekTuiRoute;
  "/download": typeof DownloadRoute;
  "/fx": typeof FxRoute;
  "/gemini": typeof GeminiRoute;
  "/goose": typeof GooseRoute;
  "/grok": typeof GrokRoute;
  "/kimi": typeof KimiRoute;
  "/mistral-vibe": typeof MistralVibeRoute;
  "/opencode": typeof OpencodeRoute;
  "/pi": typeof PiRoute;
  "/privacy": typeof PrivacyRoute;
  "/terms": typeof TermsRoute;
  "/alternatives/claude-desktop": typeof AlternativesClaudeDesktopRoute;
  "/alternatives/codex-app": typeof AlternativesCodexAppRoute;
  "/alternatives/conductor": typeof AlternativesConductorRoute;
  "/alternatives/happy-coder": typeof AlternativesHappyCoderRoute;
  "/alternatives/openchamber": typeof AlternativesOpenchamberRoute;
  "/alternatives/opencode-desktop": typeof AlternativesOpencodeDesktopRoute;
  "/alternatives/superset": typeof AlternativesSupersetRoute;
  "/docs/$": typeof DocsSplatRoute;
  "/docs": typeof DocsIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/agents": typeof AgentsRoute;
  "/amp": typeof AmpRoute;
  "/changelog": typeof ChangelogRoute;
  "/claude-code": typeof ClaudeCodeRoute;
  "/cline": typeof ClineRoute;
  "/codex": typeof CodexRoute;
  "/copilot": typeof CopilotRoute;
  "/cursor": typeof CursorRoute;
  "/deepseek-tui": typeof DeepseekTuiRoute;
  "/docs": typeof DocsRouteWithChildren;
  "/download": typeof DownloadRoute;
  "/fx": typeof FxRoute;
  "/gemini": typeof GeminiRoute;
  "/goose": typeof GooseRoute;
  "/grok": typeof GrokRoute;
  "/kimi": typeof KimiRoute;
  "/mistral-vibe": typeof MistralVibeRoute;
  "/opencode": typeof OpencodeRoute;
  "/pi": typeof PiRoute;
  "/privacy": typeof PrivacyRoute;
  "/terms": typeof TermsRoute;
  "/alternatives/claude-desktop": typeof AlternativesClaudeDesktopRoute;
  "/alternatives/codex-app": typeof AlternativesCodexAppRoute;
  "/alternatives/conductor": typeof AlternativesConductorRoute;
  "/alternatives/happy-coder": typeof AlternativesHappyCoderRoute;
  "/alternatives/openchamber": typeof AlternativesOpenchamberRoute;
  "/alternatives/opencode-desktop": typeof AlternativesOpencodeDesktopRoute;
  "/alternatives/superset": typeof AlternativesSupersetRoute;
  "/docs/$": typeof DocsSplatRoute;
  "/docs/": typeof DocsIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/agents"
    | "/amp"
    | "/changelog"
    | "/claude-code"
    | "/cline"
    | "/codex"
    | "/copilot"
    | "/cursor"
    | "/deepseek-tui"
    | "/docs"
    | "/download"
    | "/fx"
    | "/gemini"
    | "/goose"
    | "/grok"
    | "/kimi"
    | "/mistral-vibe"
    | "/opencode"
    | "/pi"
    | "/privacy"
    | "/terms"
    | "/alternatives/claude-desktop"
    | "/alternatives/codex-app"
    | "/alternatives/conductor"
    | "/alternatives/happy-coder"
    | "/alternatives/openchamber"
    | "/alternatives/opencode-desktop"
    | "/alternatives/superset"
    | "/docs/$"
    | "/docs/";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/agents"
    | "/amp"
    | "/changelog"
    | "/claude-code"
    | "/cline"
    | "/codex"
    | "/copilot"
    | "/cursor"
    | "/deepseek-tui"
    | "/download"
    | "/fx"
    | "/gemini"
    | "/goose"
    | "/grok"
    | "/kimi"
    | "/mistral-vibe"
    | "/opencode"
    | "/pi"
    | "/privacy"
    | "/terms"
    | "/alternatives/claude-desktop"
    | "/alternatives/codex-app"
    | "/alternatives/conductor"
    | "/alternatives/happy-coder"
    | "/alternatives/openchamber"
    | "/alternatives/opencode-desktop"
    | "/alternatives/superset"
    | "/docs/$"
    | "/docs";
  id:
    | "__root__"
    | "/"
    | "/agents"
    | "/amp"
    | "/changelog"
    | "/claude-code"
    | "/cline"
    | "/codex"
    | "/copilot"
    | "/cursor"
    | "/deepseek-tui"
    | "/docs"
    | "/download"
    | "/fx"
    | "/gemini"
    | "/goose"
    | "/grok"
    | "/kimi"
    | "/mistral-vibe"
    | "/opencode"
    | "/pi"
    | "/privacy"
    | "/terms"
    | "/alternatives/claude-desktop"
    | "/alternatives/codex-app"
    | "/alternatives/conductor"
    | "/alternatives/happy-coder"
    | "/alternatives/openchamber"
    | "/alternatives/opencode-desktop"
    | "/alternatives/superset"
    | "/docs/$"
    | "/docs/";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  AgentsRoute: typeof AgentsRoute;
  AmpRoute: typeof AmpRoute;
  ChangelogRoute: typeof ChangelogRoute;
  ClaudeCodeRoute: typeof ClaudeCodeRoute;
  ClineRoute: typeof ClineRoute;
  CodexRoute: typeof CodexRoute;
  CopilotRoute: typeof CopilotRoute;
  CursorRoute: typeof CursorRoute;
  DeepseekTuiRoute: typeof DeepseekTuiRoute;
  DocsRoute: typeof DocsRouteWithChildren;
  DownloadRoute: typeof DownloadRoute;
  FxRoute: typeof FxRoute;
  GeminiRoute: typeof GeminiRoute;
  GooseRoute: typeof GooseRoute;
  GrokRoute: typeof GrokRoute;
  KimiRoute: typeof KimiRoute;
  MistralVibeRoute: typeof MistralVibeRoute;
  OpencodeRoute: typeof OpencodeRoute;
  PiRoute: typeof PiRoute;
  PrivacyRoute: typeof PrivacyRoute;
  TermsRoute: typeof TermsRoute;
  AlternativesClaudeDesktopRoute: typeof AlternativesClaudeDesktopRoute;
  AlternativesCodexAppRoute: typeof AlternativesCodexAppRoute;
  AlternativesConductorRoute: typeof AlternativesConductorRoute;
  AlternativesHappyCoderRoute: typeof AlternativesHappyCoderRoute;
  AlternativesOpenchamberRoute: typeof AlternativesOpenchamberRoute;
  AlternativesOpencodeDesktopRoute: typeof AlternativesOpencodeDesktopRoute;
  AlternativesSupersetRoute: typeof AlternativesSupersetRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/agents": {
      id: "/agents";
      path: "/agents";
      fullPath: "/agents";
      preLoaderRoute: typeof AgentsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/amp": {
      id: "/amp";
      path: "/amp";
      fullPath: "/amp";
      preLoaderRoute: typeof AmpRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/changelog": {
      id: "/changelog";
      path: "/changelog";
      fullPath: "/changelog";
      preLoaderRoute: typeof ChangelogRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/claude-code": {
      id: "/claude-code";
      path: "/claude-code";
      fullPath: "/claude-code";
      preLoaderRoute: typeof ClaudeCodeRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/cline": {
      id: "/cline";
      path: "/cline";
      fullPath: "/cline";
      preLoaderRoute: typeof ClineRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/codex": {
      id: "/codex";
      path: "/codex";
      fullPath: "/codex";
      preLoaderRoute: typeof CodexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/copilot": {
      id: "/copilot";
      path: "/copilot";
      fullPath: "/copilot";
      preLoaderRoute: typeof CopilotRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/cursor": {
      id: "/cursor";
      path: "/cursor";
      fullPath: "/cursor";
      preLoaderRoute: typeof CursorRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/deepseek-tui": {
      id: "/deepseek-tui";
      path: "/deepseek-tui";
      fullPath: "/deepseek-tui";
      preLoaderRoute: typeof DeepseekTuiRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/docs": {
      id: "/docs";
      path: "/docs";
      fullPath: "/docs";
      preLoaderRoute: typeof DocsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/download": {
      id: "/download";
      path: "/download";
      fullPath: "/download";
      preLoaderRoute: typeof DownloadRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/fx": {
      id: "/fx";
      path: "/fx";
      fullPath: "/fx";
      preLoaderRoute: typeof FxRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/gemini": {
      id: "/gemini";
      path: "/gemini";
      fullPath: "/gemini";
      preLoaderRoute: typeof GeminiRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/goose": {
      id: "/goose";
      path: "/goose";
      fullPath: "/goose";
      preLoaderRoute: typeof GooseRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/grok": {
      id: "/grok";
      path: "/grok";
      fullPath: "/grok";
      preLoaderRoute: typeof GrokRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/kimi": {
      id: "/kimi";
      path: "/kimi";
      fullPath: "/kimi";
      preLoaderRoute: typeof KimiRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/mistral-vibe": {
      id: "/mistral-vibe";
      path: "/mistral-vibe";
      fullPath: "/mistral-vibe";
      preLoaderRoute: typeof MistralVibeRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/opencode": {
      id: "/opencode";
      path: "/opencode";
      fullPath: "/opencode";
      preLoaderRoute: typeof OpencodeRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/pi": {
      id: "/pi";
      path: "/pi";
      fullPath: "/pi";
      preLoaderRoute: typeof PiRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/privacy": {
      id: "/privacy";
      path: "/privacy";
      fullPath: "/privacy";
      preLoaderRoute: typeof PrivacyRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/terms": {
      id: "/terms";
      path: "/terms";
      fullPath: "/terms";
      preLoaderRoute: typeof TermsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/alternatives/claude-desktop": {
      id: "/alternatives/claude-desktop";
      path: "/alternatives/claude-desktop";
      fullPath: "/alternatives/claude-desktop";
      preLoaderRoute: typeof AlternativesClaudeDesktopRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/alternatives/codex-app": {
      id: "/alternatives/codex-app";
      path: "/alternatives/codex-app";
      fullPath: "/alternatives/codex-app";
      preLoaderRoute: typeof AlternativesCodexAppRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/alternatives/conductor": {
      id: "/alternatives/conductor";
      path: "/alternatives/conductor";
      fullPath: "/alternatives/conductor";
      preLoaderRoute: typeof AlternativesConductorRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/alternatives/happy-coder": {
      id: "/alternatives/happy-coder";
      path: "/alternatives/happy-coder";
      fullPath: "/alternatives/happy-coder";
      preLoaderRoute: typeof AlternativesHappyCoderRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/alternatives/openchamber": {
      id: "/alternatives/openchamber";
      path: "/alternatives/openchamber";
      fullPath: "/alternatives/openchamber";
      preLoaderRoute: typeof AlternativesOpenchamberRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/alternatives/opencode-desktop": {
      id: "/alternatives/opencode-desktop";
      path: "/alternatives/opencode-desktop";
      fullPath: "/alternatives/opencode-desktop";
      preLoaderRoute: typeof AlternativesOpencodeDesktopRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/alternatives/superset": {
      id: "/alternatives/superset";
      path: "/alternatives/superset";
      fullPath: "/alternatives/superset";
      preLoaderRoute: typeof AlternativesSupersetRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/docs/": {
      id: "/docs/";
      path: "/";
      fullPath: "/docs/";
      preLoaderRoute: typeof DocsIndexRouteImport;
      parentRoute: typeof DocsRoute;
    };
    "/docs/$": {
      id: "/docs/$";
      path: "/$";
      fullPath: "/docs/$";
      preLoaderRoute: typeof DocsSplatRouteImport;
      parentRoute: typeof DocsRoute;
    };
  }
}

interface DocsRouteChildren {
  DocsSplatRoute: typeof DocsSplatRoute;
  DocsIndexRoute: typeof DocsIndexRoute;
}

const DocsRouteChildren: DocsRouteChildren = {
  DocsSplatRoute: DocsSplatRoute,
  DocsIndexRoute: DocsIndexRoute,
};

const DocsRouteWithChildren = DocsRoute._addFileChildren(DocsRouteChildren);

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentsRoute: AgentsRoute,
  AmpRoute: AmpRoute,
  ChangelogRoute: ChangelogRoute,
  ClaudeCodeRoute: ClaudeCodeRoute,
  ClineRoute: ClineRoute,
  CodexRoute: CodexRoute,
  CopilotRoute: CopilotRoute,
  CursorRoute: CursorRoute,
  DeepseekTuiRoute: DeepseekTuiRoute,
  DocsRoute: DocsRouteWithChildren,
  DownloadRoute: DownloadRoute,
  FxRoute: FxRoute,
  GeminiRoute: GeminiRoute,
  GooseRoute: GooseRoute,
  GrokRoute: GrokRoute,
  KimiRoute: KimiRoute,
  MistralVibeRoute: MistralVibeRoute,
  OpencodeRoute: OpencodeRoute,
  PiRoute: PiRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  AlternativesClaudeDesktopRoute: AlternativesClaudeDesktopRoute,
  AlternativesCodexAppRoute: AlternativesCodexAppRoute,
  AlternativesConductorRoute: AlternativesConductorRoute,
  AlternativesHappyCoderRoute: AlternativesHappyCoderRoute,
  AlternativesOpenchamberRoute: AlternativesOpenchamberRoute,
  AlternativesOpencodeDesktopRoute: AlternativesOpencodeDesktopRoute,
  AlternativesSupersetRoute: AlternativesSupersetRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

import type { getRouter } from "./router.tsx";
import type { createStart } from "@tanstack/react-start";
declare module "@tanstack/react-start" {
  interface Register {
    ssr: true;
    router: Awaited<ReturnType<typeof getRouter>>;
  }
}
