//! Embeds the drizzle-generated migrations into the binary and makes Cargo
//! track the locale catalog read by rust-i18n's proc macro.
//!
//! `db/migrations/*.sql` is authored by `bun run db:generate` from
//! `db/schema.ts`. This script collects them in filename order and emits a
//! table that `persistence::apply_migrations` applies at startup, so a shipped
//! app never needs the `db` directory on disk.

use std::path::Path;
use std::{env, fs};

fn main() {
    let repository = Path::new(env!("CARGO_MANIFEST_DIR")).join("../..");
    let directory = repository.join("db/migrations");
    println!("cargo:rerun-if-changed={}", directory.display());
    println!(
        "cargo:rerun-if-changed={}",
        repository.join("locales").display()
    );

    let mut migrations = fs::read_dir(&directory)
        .unwrap_or_else(|error| panic!("reading {}: {error}", directory.display()))
        .filter_map(Result::ok)
        .filter_map(|entry| {
            let path = entry.path();
            if path.extension()? != "sql" {
                return None;
            }
            let tag = path.file_stem()?.to_str()?.to_owned();
            // drizzle names files `0000_initial_schema`. The prefix is the
            // apply order, so a file without one would sort unpredictably.
            let index: u32 = tag
                .split('_')
                .next()
                .and_then(|prefix| prefix.parse().ok())
                .unwrap_or_else(|| panic!("migration {tag} has no numeric prefix"));
            Some((index, tag, path))
        })
        .collect::<Vec<_>>();
    migrations.sort_by_key(|(index, ..)| *index);

    let mut source = String::from(
        "/// Migrations in apply order, generated by build.rs from db/migrations.\n\
         pub static MIGRATIONS: &[(&str, &str)] = &[\n",
    );
    for (position, (index, tag, path)) in migrations.iter().enumerate() {
        assert_eq!(
            *index as usize, position,
            "migration {tag} breaks the sequence; expected prefix {position:04}"
        );
        let sql = fs::read_to_string(path)
            .unwrap_or_else(|error| panic!("reading {}: {error}", path.display()));
        assert!(!sql.trim().is_empty(), "migration {tag} is empty");
        println!("cargo:rerun-if-changed={}", path.display());
        source.push_str(&format!(
            "    ({tag:?}, include_str!({:?})),\n",
            path.canonicalize().unwrap_or_else(|_| path.clone())
        ));
    }
    source.push_str("];\n");

    let out = Path::new(&env::var("OUT_DIR").expect("OUT_DIR")).join("migrations.rs");
    fs::write(&out, source).unwrap_or_else(|error| panic!("writing {}: {error}", out.display()));
}
